version: "3.8"
services:
  database:
    container_name: "postgres"
    image: postgres
    environment:
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "testpass"
      POSTGRES_DB: "library"
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
  server:
    container_name: "library-controller"
    build: .
    ports:
      - "8080:8080"